version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123

    ports:
      - "27017:27017"
